### ISSUE TITLE
Inspect is not a function, Inspect.default is

### ISSUE THREAD

**Issue by effulgentsia** [antfu/vite-plugin-inspect#100]
### Describe the bug

The README says that
```
import Inspect from 'vite-plugin-inspect'

export default {
  plugins: [
    Inspect()
  ],
}
```

should work.  When I do that, I get:
```
TypeError: (0 , import_vite_plugin_inspect.default) is not a function
```

The following works but doesn't match the README:
```
import Inspect from 'vite-plugin-inspect'

export default {
  plugins: [
    Inspect.default()
  ],
}
```

### Reproduction

See the description

### System Info

```Shell
Node 18
Vite 5.0.4
Vite Plugin Inspect 0.8.0
Bun 1.0.14
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
> Maybe caused by #99, /cc @userquin

I'll check it

**Comment by userquin** [comment]
vite + vanilla-ts in SB:

![imagen](https://github.com/antfu/vite-plugin-inspect/assets/6311119/38ef9543-66f6-4ec1-87f6-7416ed9644ea)

**Comment by userquin** [comment]
ok, problems with CJS, we should patch cjs/d.cts: https://stackblitz.com/edit/vitejs-vite-9ncgh5?file=main.js

![imagen](https://github.com/antfu/vite-plugin-inspect/assets/6311119/a961fa0a-450a-46e3-980b-020ef72d6ccf)

**Comment by userquin** [comment]
fixed: SB repo using `vite-plugin-inspect v0.8.1` https://stackblitz.com/edit/vitejs-vite-xmxn4k

**Comment by spaceemotion** [comment]
I somehow am getting the same error in a Storybook 8 vite project. I have `vite@5.1.6` installed, as well as `vite-plugin-inspect@0.8.3`.

```
info => Starting manager..
info => Starting preview..
=> Failed to build the preview
TypeError: (0 , import_vite_plugin_inspect.default) is not a function
    at Object.viteFinal (./.storybook/main.mjs:172:28)
    at ./node_modules/@storybook/core-common/dist/index.js:12:1162
    at async createViteServer (./node_modules/@storybook/builder-vite/dist/index.js:55:11517)
    at async Module.start (./node_modules/@storybook/builder-vite/dist/index.js:58:1102)
    at async storybookDevServer (./node_modules/@storybook/core-server/dist/index.js:28:7699)
    at async buildOrThrow (./node_modules/@storybook/core-server/dist/index.js:24:7665)
    at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:66:1322)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:28:3579)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:663:563)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:665:250)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

I added the plugin like so:

```ts
import Inspect from 'vite-plugin-inspect';

const config = {
  // ...
  viteFinal(config) {
    config.plugins.unshift(Inspect());

    return config;
  },
};
```

**Comment by spaceemotion** [comment]
As you can see from the stacktrace, the file already is named `main.mjs` - and yes, i already tried Inspect.default() as well. 

I just tried to delete the build cache and rebuild the whole thing again, and the `.default()` fix seems to work with that now? weird.
Interestingly enough, it runs on the storybook port (and not the one declared in the README of this package).

**Comment by userquin** [comment]
> I just tried to delete the build cache and rebuild the whole thing again, and the `.default()` fix seems to work with that now? weird.

We've moved the package to ESM first, since the package is using default export for the plugin, CJS and ESM don't play well together, we need to update the readme file to include the `.default` suffix when using this plugin in CJS.

> Interestingly enough, it runs on the storybook port (and not the one declared in the README of this package).

This plugin doesn't start a dev server, it just add a middleware to it (sirv iirc) to serve the client ui under `<base>__inspect`: https://github.com/antfu/vite-plugin-inspect/blob/67e702f998da6aed6474a0b29cd4b784b3ccf1ae/src/node/index.ts#L120-L123
